version: '2.1'
services:
  neo4j:
    build: ./neo4j
    ports:
     - "7474:7474"
     - "7687:7687"
    user: 1000:1000
    environment:
     - EXTENSION_SCRIPT=/neo4j/neo4j-init.sh
     - NEO4J_dbms_security_procedures_unrestricted=gds.*
     - NEO4J_dbms_security_procedures_whitelist=gds.*
     - NEO4J_apoc_import_file_enabled=true
     - NEO4J_apoc_export_file_enabled=true
     - NEO4J_dbms_shell_enabled=true
     - NEO4J_AUTH=neo4j/neo4jtest
    volumes:
     - ./neo4j:/neo4j
     #- ./neo4j/logs:/logs
     - ./neo4j/conf:/var/lib/neo4j/conf
    networks:
     - server
  x2:
    ports:
     - "3000:3000"
    image: g2glab/x2
    #volumes:
    # - ./config:/home/node/app/config
    links:
     - neo4j:neo4j
    networks:
     - server
networks:
  server:
